//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AddToCartTable
{
    public int tempId { get; set; }
    public string UserUniqueKey { get; set; }
    public Nullable<int> ProductID { get; set; }
    public System.DateTime created_at { get; set; }

    public virtual ProductTable ProductTable { get; set; }
}

public partial class BrandTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BrandTable()
    {
        this.ProductTables = new HashSet<ProductTable>();
    }

    public int BrandID { get; set; }
    public string BrandName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductTable> ProductTables { get; set; }
}

public partial class CategoryTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CategoryTable()
    {
        this.ProductTables = new HashSet<ProductTable>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductTable> ProductTables { get; set; }
}

public partial class MainOrderTable
{
    public int UserID { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }
    public string address { get; set; }
    public string phoneNo { get; set; }
    public System.DateTime createdAt { get; set; }
}

public partial class OrderDetailTable
{
    public int tempId { get; set; }
    public int ProductID { get; set; }
    public decimal ProductPrice { get; set; }
    public string useruniqueID { get; set; }
}

public partial class ProductTable
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductTable()
    {
        this.AddToCartTables = new HashSet<AddToCartTable>();
    }

    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public decimal ProductPrice { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductImage { get; set; }
    public Nullable<int> WatchDiameter { get; set; }
    public Nullable<int> WatchBandSize { get; set; }
    public string Description { get; set; }
    public string Fragnance { get; set; }
    public Nullable<int> RingSize { get; set; }
    public Nullable<int> RingWidth { get; set; }
    public string RingColor { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string watchBandColor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AddToCartTable> AddToCartTables { get; set; }
    public virtual BrandTable BrandTable { get; set; }
    public virtual CategoryTable CategoryTable { get; set; }
}

public partial class userTable
{
    public int UserID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public bool Status { get; set; }
}

public partial class AddBrand_Result
{
    public int BrandID { get; set; }
    public string BrandName { get; set; }
}

public partial class AddCategory_Result
{
    public int CategoryID { get; set; }
    public string CategoryName { get; set; }
}

public partial class DoLogin_Result
{
    public int UserID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public bool Status { get; set; }
}

public partial class FilterProductbyBrand_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public decimal ProductPrice { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductImage { get; set; }
    public Nullable<int> WatchDiameter { get; set; }
    public Nullable<int> WatchBandSize { get; set; }
    public string Description { get; set; }
    public string Fragnance { get; set; }
    public Nullable<int> RingSize { get; set; }
    public Nullable<int> RingWidth { get; set; }
    public string RingColor { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string watchBandColor { get; set; }
    public string BrandName { get; set; }
}

public partial class getBrand_Result
{
    public int BrandID { get; set; }
    public string BrandName { get; set; }
}

public partial class getCartProduct_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public decimal ProductPrice { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductImage { get; set; }
    public Nullable<int> WatchDiameter { get; set; }
    public Nullable<int> WatchBandSize { get; set; }
    public string Description { get; set; }
    public string Fragnance { get; set; }
    public Nullable<int> RingSize { get; set; }
    public Nullable<int> RingWidth { get; set; }
    public string RingColor { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string watchBandColor { get; set; }
}

public partial class getCategory_Result
{
    public int CategoryID { get; set; }
    public string CategoryName { get; set; }
}

public partial class getProductList_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public decimal ProductPrice { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductImage { get; set; }
    public Nullable<int> WatchDiameter { get; set; }
    public Nullable<int> WatchBandSize { get; set; }
    public string Description { get; set; }
    public string Fragnance { get; set; }
    public Nullable<int> RingSize { get; set; }
    public Nullable<int> RingWidth { get; set; }
    public string RingColor { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string watchBandColor { get; set; }
    public string brandName { get; set; }
    public string categoryName { get; set; }
}

public partial class getUsers_Result
{
    public int UserID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public bool Status { get; set; }
}

public partial class Productfilter_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public decimal ProductPrice { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductImage { get; set; }
    public Nullable<int> WatchDiameter { get; set; }
    public Nullable<int> WatchBandSize { get; set; }
    public string Description { get; set; }
    public string Fragnance { get; set; }
    public Nullable<int> RingSize { get; set; }
    public Nullable<int> RingWidth { get; set; }
    public string RingColor { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string watchBandColor { get; set; }
    public string BrandName { get; set; }
}
